-- Production extensions for multi-tenant MediKL SaaS.
-- Apply after the base schema to support admin-controlled tracking policies.

CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id INTEGER NOT NULL REFERENCES public.users_client(id) ON DELETE CASCADE,
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    tracking_enabled BOOLEAN NOT NULL DEFAULT false,
    frequency_seconds INTEGER NOT NULL DEFAULT 60 CHECK (frequency_seconds >= 15),
    location_required_for_orders BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (user_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_user_settings_company_user
    ON public.user_settings(company_id, user_id);

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for user_settings" ON public.user_settings;
CREATE POLICY "Allow all operations for user_settings"
    ON public.user_settings FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS public.location_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES public.users_client(id) ON DELETE CASCADE,
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    accuracy DECIMAL(10, 2),
    employee_name VARCHAR(120),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_location_logs_company_time
    ON public.location_logs(company_id, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_location_logs_user_time
    ON public.location_logs(user_id, timestamp DESC);

ALTER TABLE public.location_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for location_logs" ON public.location_logs;
CREATE POLICY "Allow all operations for location_logs"
    ON public.location_logs FOR ALL USING (true);

INSERT INTO public.user_settings (
    user_id,
    company_id,
    tracking_enabled,
    frequency_seconds,
    location_required_for_orders
)
SELECT
    u.id,
    u.company_id,
    u.tracking_enabled,
    u.frequency_seconds,
    u.location_required_for_orders
FROM public.users_client u
ON CONFLICT (user_id, company_id) DO NOTHING;
